### ISSUE TITLE
Nikto failed and couldn't report a failure to the Engine

### ISSUE THREAD

**Issue by rseedorff** [secureCodeBox/scanner-webserver-nikto#3]
Task Example with bodgeIT:
```
PROCESS_TARGETS="[{\"name\":\"BodgeIT Public Host\",\"location\":\"bodgeit\",\"attributes\":{\"NIKTO_PORTS\":\"8080\"}}]"
```

Nikto console output:
```
I, [2018-06-27T15:16:37.484015 #1]  INFO -- : Started scan 4ff2b893-7a1c-11e8-a431-0242ac120005
W, [2018-06-27T15:16:51.722733 #1]  WARN -- : Failed to perform scan 4ff2b893-7a1c-11e8-a431-0242ac120005
W, [2018-06-27T15:16:51.722769 #1]  WARN -- : Missing or stray quote in line 3 (CSV::MalformedCSVError)
/usr/local/lib/ruby/2.5.0/csv.rb:1874:in `block (2 levels) in shift'
/usr/local/lib/ruby/2.5.0/csv.rb:1867:in `each'
/usr/local/lib/ruby/2.5.0/csv.rb:1867:in `block in shift'
/usr/local/lib/ruby/2.5.0/csv.rb:1821:in `loop'
/usr/local/lib/ruby/2.5.0/csv.rb:1821:in `shift'
/usr/local/lib/ruby/2.5.0/csv.rb:1763:in `each'
/usr/local/lib/ruby/2.5.0/csv.rb:1777:in `to_a'
/usr/local/lib/ruby/2.5.0/csv.rb:1777:in `read'
/usr/local/lib/ruby/2.5.0/csv.rb:1314:in `parse'
/sectools/src/nikto_scan.rb:74:in `import_results'
/sectools/src/nikto_scan.rb:30:in `start'
/sectools/src/nikto_worker.rb:20:in `block in work'
/sectools/src/nikto_worker.rb:18:in `map'
/sectools/src/nikto_worker.rb:18:in `work'
/sectools/lib/camunda_worker.rb:70:in `tick'
/sectools/lib/camunda_worker.rb:48:in `block (2 levels) in initialize'
/sectools/lib/camunda_worker.rb:45:in `loop'
/sectools/lib/camunda_worker.rb:45:in `block in initialize'
W, [2018-06-27T15:16:51.722819 #1]  WARN -- : ["/usr/local/lib/ruby/2.5.0/csv.rb:1874:in `block (2 levels) in shift'", "/usr/local/lib/ruby/2.5.0/csv.rb:1867:in `each'", "/usr/local/lib/ruby/2.5.0/csv.rb:1867:in `block in shift'", "/usr/local/lib/ruby/2.5.0/csv.rb:1821:in `loop'", "/usr/local/lib/ruby/2.5.0/csv.rb:1821:in `shift'", "/usr/local/lib/ruby/2.5.0/csv.rb:1763:in `each'", "/usr/local/lib/ruby/2.5.0/csv.rb:1777:in `to_a'", "/usr/local/lib/ruby/2.5.0/csv.rb:1777:in `read'", "/usr/local/lib/ruby/2.5.0/csv.rb:1314:in `parse'", "/sectools/src/nikto_scan.rb:74:in `import_results'", "/sectools/src/nikto_scan.rb:30:in `start'", "/sectools/src/nikto_worker.rb:20:in `block in work'", "/sectools/src/nikto_worker.rb:18:in `map'", "/sectools/src/nikto_worker.rb:18:in `work'", "/sectools/lib/camunda_worker.rb:70:in `tick'", "/sectools/lib/camunda_worker.rb:48:in `block (2 levels) in initialize'", "/sectools/lib/camunda_worker.rb:45:in `loop'", "/sectools/lib/camunda_worker.rb:45:in `block in initialize'"]
W, [2018-06-27T15:16:51.722848 #1]  WARN -- : Task will be unlocked for further tries.
W, [2018-06-27T15:16:51.742690 #1]  WARN -- : Failed to submit failure for Job 4ff2b893-7a1c-11e8-a431-0242ac120005 to the Engine.
```

Expected Result:
- Nikto should return a result instead of failing silent
- If Nikto fails during the scan the scanner must return the process state 'failure'

**Comment by J12934** [comment]
Okay there were two issues here:

1. Nikto was always producing invalid csv's. I reported this and it got fixed in under 30min 😉 (https://github.com/sullo/nikto/issues/547)
2. Nikto & Arachni were still using the native camunda api and had a bug in there preventing the submission of failures.

Should both be fixed now.
